# Generated by Django 2.0.5 on 2019-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectMessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='NS',
            field=models.CharField(max_length=50, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='Title',
            field=models.CharField(max_length=50, null=True, verbose_name='标题'),
        ),
    ]
