# Generated by Django 2.0.5 on 2019-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('log_date', models.DateTimeField()),
            ],
        ),
    ]
